//! Proof artifact and verification result types.

use crate::types::{BackendTag, ProofId, QueryId, SnapshotId};
use serde::{Deserialize, Serialize};

// ─────────────────────────────────────────────────────────────────────────────
// ProofSystemKind — explicit label on what cryptographic guarantees exist
// ─────────────────────────────────────────────────────────────────────────────

/// Describes the actual proof system used to generate an artifact.
///
/// This enum is the single source of truth for what cryptographic properties
/// a `ProofArtifact` actually carries. It is included in every artifact and
/// every `VerificationResult` so downstream consumers can reason about
/// security properties without inspecting backend internals.
///
/// ### Ordering from weakest to strongest guarantees
///
/// `None` < `HashChainAudit` < `Plonky2Snark` ≈ `Halo2Snark` < (future recursive)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProofSystemKind {
    /// No proof system. Used by MockBackend.
    /// - is_zero_knowledge: false
    /// - is_succinct: false
    /// - has_real_constraints: false
    None,

    /// Hash-chain audit log produced by ConstraintCheckedBackend.
    ///
    /// - is_zero_knowledge: false  (verifier sees witness digests)
    /// - is_succinct: false        (verification is O(columns × rows))
    /// - has_real_constraints: true (operator invariants are enforced)
    /// - has_polynomial_commitments: false
    /// - has_elliptic_curves: false
    HashChainAudit,

    /// Plonky2 SNARK (FRI-based, Goldilocks field).
    ///
    /// - is_zero_knowledge: true (with blinding)
    /// - is_succinct: true (O(log n) verification)
    /// - has_real_constraints: true
    /// - has_polynomial_commitments: true (FRI)
    /// - has_elliptic_curves: false
    Plonky2Snark,

    /// Halo2 SNARK (IPA / KZG based).
    ///
    /// - is_zero_knowledge: true
    /// - is_succinct: true
    /// - has_real_constraints: true
    /// - has_polynomial_commitments: true (KZG or IPA)
    /// - has_elliptic_curves: true
    Halo2Snark,
}

impl ProofSystemKind {
    /// Whether proofs generated by this system carry a zero-knowledge property.
    pub fn is_zero_knowledge(&self) -> bool {
        matches!(self, Self::Plonky2Snark | Self::Halo2Snark)
    }

    /// Whether verification is succinct (sub-linear in witness size).
    pub fn is_succinct(&self) -> bool {
        matches!(self, Self::Plonky2Snark | Self::Halo2Snark)
    }

    /// Whether real operator constraints (sort order, group boundaries, etc.)
    /// are enforced during proving.
    pub fn has_real_constraints(&self) -> bool {
        matches!(self, Self::HashChainAudit | Self::Plonky2Snark | Self::Halo2Snark)
    }

    /// Whether a polynomial commitment scheme is used.
    pub fn has_polynomial_commitments(&self) -> bool {
        matches!(self, Self::Plonky2Snark | Self::Halo2Snark)
    }

    /// Human-readable summary for display in benchmark output and API responses.
    pub fn display_summary(&self) -> &'static str {
        match self {
            Self::None =>
                "No proof system (mock/stub only)",
            Self::HashChainAudit =>
                "Hash-chain audit (real constraints, NOT zero-knowledge, NOT succinct)",
            Self::Plonky2Snark =>
                "Plonky2 SNARK (FRI-based, Goldilocks, zero-knowledge, succinct)",
            Self::Halo2Snark =>
                "Halo2 SNARK (IPA/KZG, zero-knowledge, succinct)",
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public inputs
// ─────────────────────────────────────────────────────────────────────────────

/// The public inputs committed to in every proof.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicInputs {
    pub snapshot_root: [u8; 32],
    pub query_hash: [u8; 32],
    pub result_commitment: [u8; 32],
    pub result_row_count: u64,
}

impl PublicInputs {
    pub fn compute_query_hash(sql: &str) -> [u8; 32] {
        *blake3::hash(sql.as_bytes()).as_bytes()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Proof artifact
// ─────────────────────────────────────────────────────────────────────────────

/// The serializable output of a proving operation.
///
/// `proof_system` is the authoritative label on what cryptographic guarantees
/// this artifact carries. Always inspect it before making security claims.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProofArtifact {
    pub proof_id: ProofId,
    pub query_id: QueryId,
    pub snapshot_id: SnapshotId,
    pub backend: BackendTag,
    /// Explicit label on the proof system used. Do not infer from `backend`.
    pub proof_system: ProofSystemKind,
    pub proof_bytes: Vec<u8>,
    pub public_inputs: PublicInputs,
    pub verification_key_bytes: Vec<u8>,
    pub created_at_ms: u64,
}

impl ProofArtifact {
    pub fn content_hash(&self) -> [u8; 32] {
        *blake3::hash(&self.proof_bytes).as_bytes()
    }

    pub fn hex_proof(&self) -> String {
        hex::encode(&self.proof_bytes)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Verification result
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationResult {
    pub is_valid: bool,
    pub snapshot_root: [u8; 32],
    pub query_hash: [u8; 32],
    pub result_commitment: [u8; 32],
    pub backend: BackendTag,
    /// Proof system used — same label as in the artifact.
    pub proof_system: ProofSystemKind,
    pub error: Option<String>,
}

impl VerificationResult {
    pub fn valid(artifact: &ProofArtifact) -> Self {
        Self {
            is_valid: true,
            snapshot_root: artifact.public_inputs.snapshot_root,
            query_hash: artifact.public_inputs.query_hash,
            result_commitment: artifact.public_inputs.result_commitment,
            backend: artifact.backend.clone(),
            proof_system: artifact.proof_system.clone(),
            error: None,
        }
    }

    pub fn invalid(reason: impl Into<String>) -> Self {
        Self {
            is_valid: false,
            snapshot_root: [0u8; 32],
            query_hash: [0u8; 32],
            result_commitment: [0u8; 32],
            backend: BackendTag::Mock,
            proof_system: ProofSystemKind::None,
            error: Some(reason.into()),
        }
    }

    /// Construct an invalid result carrying a specific backend+system label.
    pub fn invalid_with_backend(
        reason: impl Into<String>,
        backend: BackendTag,
        proof_system: ProofSystemKind,
    ) -> Self {
        Self {
            is_valid: false,
            snapshot_root: [0u8; 32],
            query_hash: [0u8; 32],
            result_commitment: [0u8; 32],
            backend,
            proof_system,
            error: Some(reason.into()),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Verification request
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationRequest {
    pub proof_id: ProofId,
    pub expected_snapshot_root: Option<[u8; 32]>,
    pub expected_query_hash: Option<[u8; 32]>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Proof store (in-memory)
// ─────────────────────────────────────────────────────────────────────────────

use crate::types::{ZkDbError, ZkResult};
use dashmap::DashMap;
use std::sync::Arc;

pub struct InMemoryProofStore {
    proofs: Arc<DashMap<ProofId, ProofArtifact>>,
}

impl InMemoryProofStore {
    pub fn new() -> Self {
        Self { proofs: Arc::new(DashMap::new()) }
    }

    pub fn save(&self, artifact: ProofArtifact) {
        self.proofs.insert(artifact.proof_id.clone(), artifact);
    }

    pub fn get(&self, id: &ProofId) -> ZkResult<ProofArtifact> {
        self.proofs
            .get(id)
            .map(|a| a.clone())
            .ok_or_else(|| ZkDbError::internal(format!("proof not found: {}", id)))
    }

    pub fn list_for_query(&self, query_id: &QueryId) -> Vec<ProofArtifact> {
        self.proofs
            .iter()
            .filter(|a| &a.query_id == query_id)
            .map(|a| a.clone())
            .collect()
    }
}

impl Default for InMemoryProofStore {
    fn default() -> Self { Self::new() }
}
